### PR TITLE
Use strings in examples

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by rnelson0** [comment]
I don't think that this plugin cares, and they're valid barewords as is.

**Comment by ghoneycutt** [comment]
I thought I saw somewhere that Puppet is moving to using actual strings instead of barewords which then get treated as strings. I've been writing my code recently to quote the barewords.

**Comment by ghoneycutt** [comment]
@rnelson0 You are absolutely correct :)

**Comment by rnelson0** [comment]
@ghoneycutt Ugh, that will be an interesting change if they make it. Hopefully it will be an option defaulting to false for a long while.

With that in mind, if you want to note that the plugin doesn't care if they're barewords or quoted strings (and write some tests to validate that) it might be worthwhile.

**Comment by rnelson0** [comment]
Actually it looks like this is tested already at https://github.com/voxpupuli/puppet-lint-file_ensure-check/blob/master/spec/puppet-lint/plugins/check_file_ensure/check_file_ensure_spec.rb#L38 and other areas, though it's not a separate test. I think a small note would suffice, unless you want to break the tests apart.

**Comment by bastelfreak** [comment]
Hi @rnelson0 @ghoneycutt how should we proceed here?

**Comment by ffrank** [comment]
I seem to remember hearing that current styleguides actually mandate we _not_ quote `present` and friends. Pinging @tuxmea.

**Comment by ghoneycutt** [comment]
@ffrank quoting is optional as per the style guide.

https://docs.puppet.com/guides/style_guide.html#quoting

**Comment by tuxmea** [comment]
I hope Puppet does not enforce quoting of values which are symbols in the type....
And yes: it is optional.

**Comment by ffrank** [comment]
Okay, so at this points this seems quite arbitrary. I'm curious as to the substance of @ghoneycutt's original assumption. Perhaps @hlindberg can comment on the direction of the language development?

**Comment by hlindberg** [comment]
I don't see barewords going away in the Puppet Language. The only reason you want to quote bare words are if they are close to language terms - as an example, currently `protected` is not a keyword (it may never be one), but still a likely candidate should we ever want to have what it suggests in addition to 'private'. 

The rules for barewords are now specified (and implemented as specified) whereas earlier there were some murky corners that led to ambiguities. They are ok to use.

One area where barewords cause problems is in interpolation as `${xxx-yyy}` is a) `$xxx - 'yyy'`, or `$xxx-yyy` (an illegal variable name) IIRC, the implementation uses the first interpretation (stops on first non variable name acceptable character. Here, naturally quotes would help in understanding what is going on, but leaving quotes out and using barewords is not illegal.

So, use quotes where the bare word would be illegal and where leaving quotes out is harder to understand because of similarity with existing things. For example `$a = 'include'` makes it clear that the string is wanted and not a function call.

**Comment by ghoneycutt** [comment]
@hlindberg Thank you for the insight!

I think I saw something on the mailing list about quoting bare words, though it seems they are fine and the current style guide says it is optional.

In case you are curious, here are the bare words docs. https://docs.puppet.com/puppet/latest/reference/lang_data_string.html#bare-words

**Comment by hlindberg** [comment]
And here is how they are specified: https://github.com/puppetlabs/puppet-specifications/blob/master/language/lexical_structure.md#bare-words-names-and-references

**Comment by ffrank** [comment]
Thanks everyone (esp. Henrik) for clearing this up. Very good to know.

**Pull request closed without merging**
